//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab13var7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudetnsGrade = new HashSet<StudetnsGrade>();
        }
    
        public int Id_Student { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone_Number { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudetnsGrade> StudetnsGrade { get; set; }
    }
}
