//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab13var7
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudetnsGrade
    {
        public int Id_Grade { get; set; }
        public Nullable<int> Id_Student { get; set; }
        public Nullable<int> Id_Subject { get; set; }
        public int Grade { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
